appName: "terraform-reconciler"
namespace: "terraform-reconciler"

image:
  repository: ghcr.io/lukaspj/kube-tf-reconciler/kube-tf-reconciler
  tag: sha-d5cdcb6
  pullPolicy: IfNotPresent

imagePullSecrets: []

# Environment variables for the reconciler container
env:
  KREC_NAMESPACE: "terraform-reconciler"
  KREC_WORKSPACE_PATH: "/tmp/workspaces"
  AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/kubernetes.io/serviceaccount/token

